#!/usr/bin/env bash

source ./packets/packets

source ./packets/c2s_handshake

source ./packets/c2s_status
source ./packets/s2c_status

source ./protocol/varint
source ./protocol/types

declare -A player_connection=([stage]="handshake")

while true; do
    declare -A packet=$(read_packet)

    case "${player_connection[stage]}" in
        "handshake")
            handle_c2s_handshake_packet "$(xxd -r -p <<< "${packet["data"]}" | read_c2s_handshake_packet )"
            ;;
        "status") 
            case "${packet["id"]}" in
                0) # status req
                    handle_c2s_status_request "$(xxd -r -p <<< "${packet["data"]}" | read_c2s_status_request )"
                    ;;
                1) # ping req
                    ;;
                *)
                    echo "unknown status packet with id ${packet["id"]} received" >&2
                    declare -p packet >&2
                    ;;
            esac
            ;;
        *) 
            echo "Invalid protocol stage wtf get out of here" >&2;
            exit 1;
            ;;
    esac
done

