#!/usr/bin/env bash

if ! command -v ncat &>/dev/null; then
    echo "ncat binary not found" >&2
    exit 1
fi

if [[ -n $1 ]]; then
    port=$1
else
    read -r -p "Port for your local server: " port
fi

ncat -e ./main -l "$port" -k

