#!/usr/bin/env bash

read_c2s_handshake_packet() {
    local protocol_version
    local server_address
    local server_port
    local intent

    protocol_version=$(read_varint)
    server_address=$(read_string)

    local b1 b2
    b1=$(read_varint)
    b2=$(read_varint)
    server_port=$(( (b1 << 8) | b2 ))

    intent=$(read_varint)

    printf '([protocol_version]="%d" [server_address]="%s" [server_port]="%d" [intent]="%d")' "$protocol_version" "$server_address" "$server_port" "$intent"
}

handle_c2s_handshake_packet() {
    declare -A packet=$1

    case "${packet[intent]}" in
        0) # status
            player_connection["stage"]="status"
            ;;
        *) # everything else
            exit 1
            ;;
    esac
}

