#!/usr/bin/env bash

# packet id and bytes separated by comma
read_packet() {
    local len
    local packet_id

    len=$(read_varint)

    head -c "$len" | {
        packet_id=$(read_varint)
        printf '%s,' "$packet_id"
        printf '%s' "$(xxd -p)"
    }
}

